disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- identifier_name
- function_parameter_count

excluded: # paths to ignore during linting. Takes precedence over `included`.
- GameCatalogue/Base
